[package]
name = "dotfiles"
version = "0.9.0"
authors = ["Miguel Barreto <miguelandres@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = {version ="4.0.13", features = ["derive"]}
dotfiles_processor = {path = "../dotfiles_processor"}
log = "0.4.14"
simplelog = "^0.12.0"
