version: 2.1

orbs:
  rust: circleci/rust@1.6.0

executors:
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:202107-02
  macos: # macos executor running Xcode
    macos:
      xcode: 15.0.0


jobs:
  test:
    parameters:
      os:
        type: executor
      binary:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - rust/clippy
      - rust/build
      - rust/test

workflows:
  linux-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              binary: [linux]
  mac-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [macos]
              binary:
                - mac
