[package]
name = "rustybot"
version = "0.1.0"
authors = ["Miguel Barreto <miguelandres@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rustybot_core = {path = "../rustybot_core"}
log = "0.4.14"
itertools = "0.10.1"
simplelog = "^0.10.0"
