[package]
name = "dotfiles_processor"
version = "0.1.0"
authors = ["Miguel Barreto <miguelandres@users.noreply.github.com>"]
edition = "2018"

[dependencies]
dotfiles_core = {path = "../dotfiles_core"}
dotfiles_actions = {path = "../dotfiles_actions"}
log = "0.4.14"
itertools = "0.10.1"
