[package]
name = "dotfiles_core"
version = "1.0.0"
authors = ["Miguel Barreto <miguelandres@users.noreply.github.com>"]
edition = "2018"

[dependencies]
getset = "0.1.2"
home = "0.5.4"
itertools = "0.13.0"
strict-yaml-rust = "0.1.2"
subprocess = "0.2.8"
