name: Release Nightly

on:
  # Run nightly
  schedule:
    - cron: "0 0 * * *"

  # Allow for manual dispatch on GitHub
  workflow_dispatch:

jobs:
  create-nightly-release:
    name: Create Nightly Release
    runs-on: ubuntu-latest
    outputs:
      activity_check: ${{ env.GHA_REPO_ALIVE }}
      date: ${{ steps.current_time_underscores.outputs.formattedTime }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      package_prefix: dotfiles-nightly-${{ steps.current_time_underscores.outputs.formattedTime }}
    steps:
      - name: Activity check
        run: |
          :
          # Based off https://github.community/t/trigger-workflow-if-there-is-commit-in-last-24-hours/17074/3
          curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits | jq -r '[.[]][0]' > $HOME/commit.json
          date="$(jq -r '.commit.committer.date' $HOME/commit.json)"
          timestamp=$(date --utc -d "$date" +%s)
          days=$(( ( $(date --utc +%s) - $timestamp ) / 86400 ))
          author="$(jq -r '.commit.committer.name' $HOME/commit.json)"
          url="$(jq -r '.html_url' $HOME/commit.json)"
          rm -f $HOME/commit.json
          echo "Repository activity: $timestamp $author $url"
          alive=0
          if [ "${{ github.event_name }}" == "repository_dispatch" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "[WARNING] Ignoring activity check: workflow triggered manually."
            alive=1
          elif [[ $days < 1 ]]; then
            echo Repository active
            alive=1
          else
            echo "[WARNING] Repository not updated: event ${{ github.event_name }} not allowed to modify stale repository."
          fi
          if [[ $alive == 1 ]]; then
            echo "GHA_REPO_ALIVE=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Get current time with dashes
        uses: 1466587594/get-current-time@v2
        id: current_time_dashes
        with:
          format: YYYY-MM-DD

      - name: Get current time with underscores
        uses: 1466587594/get-current-time@v2
        id: current_time_underscores
        with:
          format: YYYY_MM_DD

      - name: Create release
        if: env.GHA_REPO_ALIVE == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.current_time_dashes.outputs.formattedTime }}
          release_name: Nightly ${{ steps.current_time_dashes.outputs.formattedTime }}
          prerelease: true

  build:
    name: Build ${{ matrix.target.name }}
    needs: create-nightly-release
    if: needs.create-nightly-release.outputs.activity_check == 'true'
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly]
        target:
          - name: x86_64-unknown-linux-gnu
            gh_env: ubuntu-latest
          - name: aarch64-apple-darwin
            gh_env: macos-11
          - name: x86_64-apple-darwin
            gh_env: macos-11
        include:
          - target:
              gh_env: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
          - target:
              gh_env: macos-11
            sccache-path: /Users/runner/Library/Caches/Mozilla.sccache

    env:
      PACKAGE_FILE: ${{ needs.create-nightly-release.outputs.package_prefix }}-${{ matrix.target.name }}.${{ 'tar.gz' }}
      CARGO_BUILD_DIR: target/${{ matrix.target.name }}/release
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
    runs-on: ${{ matrix.target.gh_env }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - name: Setup rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install ${{ matrix.rust}}-${{ matrix.target.name }} --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.target.name }}--nightly-release--branch--${{ github.ref }}
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package dotfiles --release --target ${{ matrix.target.name }}
        env:
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }}

      - name: Package common
        run: |
          mkdir package
          cp README.md package/README.md
          cp LICENSE.txt package/LICENSE.txt

      - name: Package Linux
        if: runner.os == 'Linux'
        run: |
          cp ${{ env.CARGO_BUILD_DIR }}/dotfiles package/dotfiles
          cd package/
          tar -czvf ../${{ env.PACKAGE_FILE }} *

      - name: Upload package
        if: runner.os != 'macOS'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-nightly-release.outputs.upload_url }}
          asset_path: ./${{ env.PACKAGE_FILE }}
          asset_name: ${{ env.PACKAGE_FILE }}
          asset_content_type: ${{ endsWith(env.PACKAGE_FILE, 'tar.gz') && 'application/gzip' || 'application/zip' }}

      - name: Upload macOS build artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.name }}
          path: |
            ${{ env.CARGO_BUILD_DIR }}/dotfiles
            package

  build-mac-universal-binary:
    name: Build macOS universal binary
    needs: [create-nightly-release, build]
    runs-on: macos-latest
    env:
      PACKAGE_FILE: ${{ needs.create-nightly-release.outputs.package_prefix }}-macos-universal.tar.gz
    steps:
      - name: Download aarch64 binary
        uses: actions/download-artifact@v2
        with:
          name: aarch64-apple-darwin

      - name: Download x86_64 binary
        uses: actions/download-artifact@v2
        with:
          name: x86_64-apple-darwin

      - name: Make universal binary
        run: |
          lipo -create -output package/dotfiles target/x86_64-apple-darwin/release/dotfiles target/aarch64-apple-darwin/release/dotfiles
          chmod +x package/dotfiles

      - name: Package macOS
        run: |
          cd package
          tar -czvf ../${{ env.PACKAGE_FILE }} *

      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-nightly-release.outputs.upload_url }}
          asset_path: ./${{ env.PACKAGE_FILE }}
          asset_name: ${{ env.PACKAGE_FILE }}
          asset_content_type: application/gzip
