name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.ref_name }}
      name: ${{ github.ref_name }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      package_prefix: dotfiles-${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: false

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md

  build-and-publish:
    name: Build and Publish
    needs: create-release
    uses: ./.github/workflows/build_and_publish.yml
    with:
      tag: ${{ needs.create-release.outputs.tag }}
      name: ${{ needs.create-release.outputs.name }}
      package_prefix: ${{ needs.create-release.outputs.package_prefix }}
