name: Rust Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install Homebrew
        run: cargo run --package rustybot_core --bin test_homebrew_install
      - name: Check homebrew is installed
        run: which brew

  build-mac-os:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install Homebrew
        run: cargo run --package rustybot_core --bin test_homebrew_install
      - name: Check homebrew is installed
        run: which brew
