name: Rust Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: ${{ matrix.make.name }} (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.gh_env }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly]
        target:
          - name: x86_64-unknown-linux-gnu
            gh_env: ubuntu-latest
          - name: aarch64-apple-darwin
            gh_env: macos-11
          - name: x86_64-apple-darwin
            gh_env: macos-11

    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target.name }}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        if: matrix.target.name != 'aarch64-apple-darwin' # cannot run aarch64 on intel
        run: cargo test --verbose --target ${{ matrix.target.name }}
      - name: Install Homebrew & ohmyzsh and check brew is installed
        if: matrix.target.name != 'aarch64-apple-darwin' # cannot run aarch64 on intel
        run: |
          cargo run --target ${{ matrix.target.name }} -- --log-level-filter debug install-homebrew
          cargo run --target ${{ matrix.target.name }} -- --log-level-filter debug install-oh-my-zsh --skip-chsh
