name: Documentation

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust}}
          target: ${{ matrix.target.name }}
          components: rustc, rust-std, cargo

      - name: Build
        uses: actions-rs/cargo@v1.0.6
        with:
          command: doc
          args: --all --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
